on:
  push:
    branches: [ master, develop, feature/** ]
  pull_request:
    branches: [ master ]
jobs:
  activerecord-test-withdb:
    runs-on: ubuntu-latest
    services:
        # mysql-service Label used to access the service container
        mysql-service:
          # Docker Hub image (also with version)
          image: mysql:5.7
          env:
            ## Accessing to Github secrets, where you can store your configuration
            MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
            MYSQL_DATABASE: db_test
          ## map the "external" 33306 port with the "internal" 3306
          ports:
            - 33306:3306
          # Set health checks to wait until mysql database has started (it takes some seconds to start)
          options: >-
            --health-cmd="mysqladmin ping"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=3
    steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
        - uses: actions/checkout@master
        - name: Elveneek activerecord setup
          run: |
            composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        - name: Execute tests via Pest
          env:
            DB_CONNECTION: mysql
            DB_DATABASE: db_test
            DB_PORT: 33306
            DB_USER: root
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          run: |
            vendor/bin/pest
